import tkinter as tk

def label(f,n,xa,ya):
    l1 = tk.Label(f,text=n)
    l1.place(x=xa, y=ya)

#-------------------- HK DATA Label Config -----------------------------------------------
label_Y_position = 50
label_Y_position_width = 23
def hklabel(x):
    label(x,u'Day                                   ',10,label_Y_position + label_Y_position_width*0)
    label(x,u'Hour                                ',10,label_Y_position + label_Y_position_width*1)
    label(x,u'Min                                 ',10,label_Y_position + label_Y_position_width*2)
    label(x,u'Sec                                   ',10,label_Y_position + label_Y_position_width*3)
    label(x,u'RESET_RAW_V',10,label_Y_position + label_Y_position_width*4)
    label(x,u'FAB_I(3V3#1)',10,label_Y_position + label_Y_position_width*5)
    label(x,u'GYRO_I(3V3#2)',10,label_Y_position + label_Y_position_width*6)
    label(x,u'UHF-COM_I(Unreg#1)',10,label_Y_position + label_Y_position_width*7)
    label(x,u'DEPANT_I(Unreg#2)',10,label_Y_position + label_Y_position_width*8)
    label(x,u'MIS_I(5V)',10,label_Y_position + label_Y_position_width*9)
    label(x,u'+X Temp                    ',10,label_Y_position + label_Y_position_width*10)
    label(x,u'-X Temp                    ',10,label_Y_position + label_Y_position_width*11)
    label(x,u'+Y Temp                    ',10,label_Y_position + label_Y_position_width*12)
    label(x,u'-Y Temp                    ',10,label_Y_position + label_Y_position_width*13)
    label(x,u'+Z Temp                    ',10,label_Y_position + label_Y_position_width*14)
    label(x,u'-Z Temp                    ',10,label_Y_position + label_Y_position_width*15)
    label(x,u'BPB temporature(degC)',10,label_Y_position + label_Y_position_width*16)
    label(x,u'-X Voltage           ',10,label_Y_position + label_Y_position_width*17)
    label(x,u'+Y Voltage           ',10,label_Y_position + label_Y_position_width*18)
    label(x,u'-Y Voltage           ',10,label_Y_position + label_Y_position_width*19)
    label(x,u'+Z Voltage           ',10,label_Y_position + label_Y_position_width*20)
    label(x,u'-Z Voltage           ',10,label_Y_position + label_Y_position_width*21)

    label(x,u'-X Current           ',230,label_Y_position + label_Y_position_width*0)
    label(x,u'+Y Current           ',230,label_Y_position + label_Y_position_width*1)
    label(x,u'-Y Current           ',230,label_Y_position + label_Y_position_width*2)
    label(x,u'+Z Current           ',230,label_Y_position + label_Y_position_width*3)    
    label(x,u'-Z Current           ',230,label_Y_position + label_Y_position_width*4)
    label(x,u'Battery Temp         ',230,label_Y_position + label_Y_position_width*5)
    label(x,u'Battery V            ',230,label_Y_position + label_Y_position_width*6)   
    label(x,u'Battery I            ',230,label_Y_position + label_Y_position_width*7)
    label(x,u'FAB Raw V            ',230,label_Y_position + label_Y_position_width*8)
    label(x,u'FAB Raw I            ',230,label_Y_position + label_Y_position_width*9)
    label(x,u'SRC V                ',230,label_Y_position + label_Y_position_width*10)
    label(x,u'SRC I                ',230,label_Y_position + label_Y_position_width*11)
    label(x,u'Heater Flag',230,label_Y_position + label_Y_position_width*12)
    label(x,u'Kill status(FAB/OBC)',230,label_Y_position + label_Y_position_width*13)
    label(x,u'RESET_RAW_V_MON',230,label_Y_position + label_Y_position_width*14)
    label(x,u'LCL_UHF_COM',230,label_Y_position + label_Y_position_width*15)
    label(x,u'LCL_5V0',230,label_Y_position + label_Y_position_width*16)
    label(x,u'DCDC_FAB',230,label_Y_position + label_Y_position_width*17)
    label(x,u'LCL_DEPANT',230,label_Y_position + label_Y_position_width*18)
    label(x,u'LCL_3V3_2',230,label_Y_position + label_Y_position_width*19)
    label(x,u'LCL_FAB',230,label_Y_position + label_Y_position_width*20)
    label(x,u'DCDC_5V0',230,label_Y_position + label_Y_position_width*21)
    label(x,u'DCDC_3V3_2',230,label_Y_position + label_Y_position_width*22)
    label(x,u'LCL_COMPIC',230,label_Y_position + label_Y_position_width*23)
    label(x,u'LCL_MAINPIC',230,label_Y_position + label_Y_position_width*24)